### ISSUE TITLE
Startup failed: character string expected as first argument

### ISSUE THREAD

**Issue by nicoFhahn** [ficonsulting/RInno#122]
Hey,
I tried to create the example app but everytime I try to launch the final product, I get the following error:

Startup failed with error(s):
character string expected as first argument

**Comment by runyoncr** [comment]
I'm having the same issue with my own shiny program, although I was able to create the example app with no problem. I'm using shinydashboard in my build; could that be a problem?

**Comment by singular-instruction** [comment]
I am getting the same error, hoping this has been resolved by someone, because I am at my wits end.

**Comment by mrderban** [comment]
same deal here ! did you guys find a solution ? splitting code in ui & server files doesn't make it for me.

**Comment by runyoncr** [comment]
Still having this problem. The solution above worked for an "in-progress" build months ago, but I've yet to successfully make Shiny apps into an .exe because this problem persists. I even tried rebuiding the my Shiny app in a "simplified" version that didn't use many additional packages (just shinyjs) and I'm still getting this message. 

I'm using the newest versions of electron, shiny, etc. (as of Sept 11 2019) and this doesn't seem to be any better.

**Comment by iadjali** [comment]
I've been facing exactly the same problem for weeks and splitting my App in UI and Server as suggested above doesn't solve it.

Can anyone help?

**Comment by cstelzne** [comment]
Possible solution: prior to building the executable, delete the following:
- all the contents of the nativefier-app directory
- any .bat/.iss files from previous builds

My particular issue was that I was changing the app_name parameter of the create_app() function, and that meant that nativefier-app was including data from several previous builds, and the old .bat/.iss files were hanging around as well. As soon as I deleted them, things went totally fine. Ymmv!

**Comment by KevinwellsPhD** [comment]
I was having this problem and I split my app into ui and server and it worked for me.

**Comment by NicWir** [comment]
I had the same issue and found that, after splitting my app.R into ui.R and server.R, I still had `ui <- fluidPage(` at the top of my UI, whereas it should start with `fluidPage(`. Hope that helps someone.

**Comment by matdillen** [comment]
I had this issue and it seemed to be caused by the default setting of using electron as browser. Setting another user_browser in create_config fixed the problem. For some reason, building the app to run in electron does not work anymore (for me).
